"""
Model 4 training: Energy-Based Model with Contrastive Divergence.

Negative samples are generated by running Langevin MCMC from a persistent
replay buffer (Du & Mordatch, NeurIPS 2019).  Calendar constraints are
enforced at every Langevin step so every negative sample is a syntactically
valid date.

Training loop:
  For each batch (X, Y⁺):
    1. Draw initial negative samples:
         - With probability p_replay: sample from replay buffer.
         - Otherwise: draw a random valid date.
    2. Run n_mcmc_steps of Langevin dynamics → Y⁻.
    3. Push Y⁻ back into the replay buffer.
    4. Compute CD loss: E(Y⁺,c) − E(Y⁻,c) + λ·reg.
    5. Back-prop and update energy network + condition encoder.

Validation metric: Condition Satisfaction Rate (CSR) — fraction of Langevin
samples that satisfy all four calendar conditions (same metric as Models 1–3).
"""
import torch
from torch.utils.data import DataLoader

from src.model_4.model import (
    DateEBM, ReplayBuffer,
    is_leap, days_in_month, day_of_week,
)


# ── CSR helper ────────────────────────────────────────────────────────────────

def _compute_csr(Y_gen: torch.Tensor, X_cond: torch.Tensor) -> float:
    """Fraction of generated dates satisfying all four constraints."""
    d, m, y = Y_gen[:, 0], Y_gen[:, 1], Y_gen[:, 2]
    dow_c, mon_c, leap_c, dec_c = (
        X_cond[:, 0], X_cond[:, 1], X_cond[:, 2], X_cond[:, 3]
    )
    ok_month = (m >= 1) & (m <= 12)
    ok_year  = y > 0
    ok_day   = ok_month & ok_year & (d >= 1) & (d <= days_in_month(m, y))
    all_ok   = (
        ok_day
        & (day_of_week(d, m, y) == dow_c)
        & ((m - 1) == mon_c)
        & (is_leap(y).long() == leap_c)
        & ((y // 10) == dec_c)
    )
    return all_ok.float().mean().item()


# ── Random valid date initialiser ────────────────────────────────────────────

def _random_valid_dates(X_cond: torch.Tensor, device: str) -> torch.Tensor:
    """
    Generate a random but constraint-satisfying date for each condition in X_cond.
    Used to seed the replay buffer and as a fallback initialisation.

    Strategy: fix decade from condition, sample a leap-valid year unit,
    fix month from condition, then pick a random day-of-week-valid day.
    """
    B         = X_cond.shape[0]
    dow_cond  = X_cond[:, 0]
    mon_cond  = X_cond[:, 1]
    leap_cond = X_cond[:, 2]
    dec_cond  = X_cond[:, 3]

    mon_pred = mon_cond + 1   # condition is 0-indexed month

    # Year unit: uniform over leap-valid digits
    y_cands     = dec_cond.unsqueeze(1) * 10 + torch.arange(10, device=device)
    valid_units = is_leap(y_cands).long() == leap_cond.unsqueeze(1)
    # Replace all-invalid rows with ones (fallback to any unit)
    all_invalid = ~valid_units.any(dim=1, keepdim=True)
    valid_units = valid_units | all_invalid
    unit_pred   = torch.multinomial(valid_units.float(), 1).squeeze(-1)
    y_pred      = dec_cond * 10 + unit_pred

    # Day: uniform over valid days that match day-of-week
    d_cands      = torch.arange(1, 32, device=device).unsqueeze(0).expand(B, 31)
    valid_bounds = d_cands <= days_in_month(mon_pred, y_pred).unsqueeze(1)
    dow_cands    = day_of_week(d_cands, mon_pred.unsqueeze(1), y_pred.unsqueeze(1))
    valid_dow    = dow_cands == dow_cond.unsqueeze(1)
    valid_days   = valid_bounds & valid_dow
    # Fallback: if no valid day found use first day
    all_bad      = ~valid_days.any(dim=1, keepdim=True)
    valid_days   = valid_days | (all_bad & (d_cands == 1))
    day_pred     = torch.multinomial(valid_days.float(), 1).squeeze(-1) + 1

    return torch.stack([day_pred, mon_pred, y_pred], dim=-1)


# ── Training loop ─────────────────────────────────────────────────────────────

def train(train_ds, val_ds, model4_cfg, train4_cfg, device: str = "cpu"):
    """
    Train Model 4 (Energy-Based Model).

    Parameters
    ----------
    train_ds   : training dataset (yields (X, Y) pairs)
    val_ds     : validation dataset
    model4_cfg : Model4Config
    train4_cfg : Train4Config
    device     : "cpu" or "cuda"

    Returns
    -------
    (model, history)
    history keys: epochs, train_loss, val_loss, e_pos, e_neg, csr
    """
    train_loader = DataLoader(
        train_ds,
        batch_size=min(train4_cfg.batch_size, len(train_ds)),
        shuffle=True,
        drop_last=True,
    )
    val_loader = DataLoader(val_ds, batch_size=256, shuffle=False)

    model = DateEBM(
        cond_dim=model4_cfg.cond_dim,
        max_decade=model4_cfg.max_decade,
        hidden_dim=model4_cfg.hidden_dim,
        n_layers=model4_cfg.n_layers,
    ).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=train4_cfg.lr)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=train4_cfg.n_epochs
    )

    replay_buffer = ReplayBuffer(capacity=train4_cfg.replay_buffer_size)

    history = {
        "epochs": [], "train_loss": [], "val_loss": [],
        "e_pos": [], "e_neg": [], "csr": [],
    }

    print(f"\n{'Epoch':>6}  {'Train Loss':>11}  {'Val Loss':>9}  "
          f"{'E+':>8}  {'E-':>8}  {'Val CSR':>8}")
    print("-" * 62)

    for epoch in range(1, train4_cfg.n_epochs + 1):
        model.train()
        epoch_loss = epoch_epos = epoch_eneg = 0.0
        n_batches  = 0

        for X_b, Y_b in train_loader:
            X_b, Y_b = X_b.to(device), Y_b.to(device)
            B = X_b.shape[0]

            # ── Draw initial negative samples ──────────────────────
            if (len(replay_buffer) >= B
                    and torch.rand(1).item() < train4_cfg.replay_prob):
                init_neg = replay_buffer.sample(B).to(device)
            else:
                init_neg = _random_valid_dates(X_b, device)

            # ── Langevin MCMC → negative samples ──────────────────
            model.eval()   # freeze BN/dropout for MCMC (energy net has none, but safe)
            with torch.enable_grad():
                Y_neg = model.langevin_sample(
                    X_b,
                    init_Y=init_neg,
                    n_steps=train4_cfg.n_mcmc_steps,
                    step_size=train4_cfg.mcmc_step_size,
                    noise_std=train4_cfg.mcmc_noise,
                    device=device,
                )
            replay_buffer.push(Y_neg.cpu())
            model.train()

            # ── CD loss and gradient step ──────────────────────────
            optimizer.zero_grad()
            loss, e_pos, e_neg = model.cd_loss(X_b, Y_b, Y_neg, train4_cfg.l2_reg)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(
                model.parameters(), train4_cfg.grad_clip
            )
            optimizer.step()

            epoch_loss += loss.item()
            epoch_epos += e_pos.item()
            epoch_eneg += e_neg.item()
            n_batches  += 1

        scheduler.step()

        # ── Validation: loss + CSR ─────────────────────────────────
        model.eval()
        val_loss_acc              = 0.0
        all_X_val, all_Y_gen      = [], []

        with torch.no_grad():
            for X_v, Y_v in val_loader:
                X_v, Y_v = X_v.to(device), Y_v.to(device)

                # Val loss uses random negatives (fast, no full Langevin)
                Y_neg_v  = _random_valid_dates(X_v, device)
                with torch.enable_grad():
                    Y_neg_v = model.langevin_sample(
                        X_v,
                        init_Y=Y_neg_v,
                        n_steps=max(10, train4_cfg.n_mcmc_steps // 4),
                        step_size=train4_cfg.mcmc_step_size,
                        noise_std=train4_cfg.mcmc_noise,
                        device=device,
                    )
                l_v, _, _ = model.cd_loss(X_v, Y_v, Y_neg_v, train4_cfg.l2_reg)
                val_loss_acc += l_v.item()

                # CSR uses full inference sample
                Y_gen_v = model.sample(
                    X_v,
                    n_samples=1,
                    device=device,
                    n_mcmc_steps=train4_cfg.n_mcmc_steps,
                    step_size=train4_cfg.mcmc_step_size,
                    noise_std=train4_cfg.mcmc_noise,
                )
                all_X_val.append(X_v.cpu())
                all_Y_gen.append(Y_gen_v.cpu())

        val_loss_avg = val_loss_acc / max(1, len(val_loader))
        X_val_cat    = torch.cat(all_X_val)
        Y_gen_cat    = torch.cat(all_Y_gen)
        csr          = _compute_csr(Y_gen_cat, X_val_cat)

        t_loss = epoch_loss / n_batches
        t_epos = epoch_epos / n_batches
        t_eneg = epoch_eneg / n_batches

        history["epochs"].append(epoch)
        history["train_loss"].append(t_loss)
        history["val_loss"].append(val_loss_avg)
        history["e_pos"].append(t_epos)
        history["e_neg"].append(t_eneg)
        history["csr"].append(csr)

        if epoch % 10 == 0 or epoch == 1 or epoch == train4_cfg.n_epochs:
            print(f"{epoch:>6}  {t_loss:>11.4f}  {val_loss_avg:>9.4f}  "
                  f"{t_epos:>8.4f}  {t_eneg:>8.4f}  {csr:>8.3f}")

    return model, history